# Generated by Django 3.0.3 on 2020-04-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('article_discription', models.CharField(max_length=250, verbose_name='Краткое описание статьи')),
                ('article_text', models.TextField(verbose_name='Текст статьи')),
                ('article_pub_date', models.DateField(verbose_name='Время публикации статьи')),
                ('article_author', models.CharField(max_length=50)),
            ],
        ),
    ]
